=== dns-gh/oodevs/data/app-data/resources/schemas/4.2.0/physical/Units.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:include schemaLocation="tools.xsd"/>
	<xs:element name="units">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="unit" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="nature">
								<xs:complexType>
									<xs:attribute name="nature" type="xs:string" use="required"/>
									<xs:attribute name="atlas-nature" type="xs:string" use="required"/>
									<xs:attribute name="level" type="xs:string" use="required"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="equipments">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="equipment" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="convoyer" type="xs:boolean"/>
												<xs:attribute name="count" type="xs:nonNegativeInteger" use="required"/>
												<xs:attribute name="type" type="xs:string" use="required"/>
												<xs:attribute name="crew" type="xs:nonNegativeInteger" use="required"/>
												<xs:attribute name="loadable" type="xs:boolean" use="optional"/>
												<xs:attribute name="major" type="xs:boolean" use="optional"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="crew-ranks">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="crew-rank" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="count" type="xs:nonNegativeInteger" use="required"/>
												<xs:attribute name="type" type="xs:string" use="required"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="logistics" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="category" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="dotation" minOccurs="0" maxOccurs="unbounded">
														<xs:complexType>
															<xs:attribute name="logistic-threshold" type="xs:nonNegativeInteger" use="required"/>
															<xs:attribute name="name" type="xs:string" use="required"/>
															<xs:attribute name="normalized-consumption" type="xs:nonNegativeInteger" use="required"/>
															<xs:attribute name="capacity" type="xs:nonNegativeInteger" use="required"/>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
												<xs:attribute name="name" type="xs:string" use="required"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="stocks" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="stock" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="category" type="xs:string" use="required"/>
												<xs:attribute name="threshold" type="xs:nonNegativeInteger" use="required"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="postures">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="posture" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="setup-time" type="T_Time" use="required"/>
												<xs:attribute name="name" type="xs:string" use="required"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="setup" minOccurs="0">
								<xs:complexType>
									<xs:attribute name="installation-time" type="T_Time" use="required"/>
									<xs:attribute name="uninstallation-time" type="T_Time" use="required"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="nbc">
								<xs:complexType>
									<xs:attribute name="decontamination-delay" type="T_Time" use="required"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="distance-before-points" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="distance-before-point" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="value" type="xs:nonNegativeInteger" use="required"/>
												<xs:attribute name="type" type="xs:string" use="required"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="drill-blow" minOccurs="0">
								<xs:complexType>
									<xs:attribute name="length" type="xs:nonNegativeInteger" use="required"/>
									<xs:attribute name="width" type="xs:nonNegativeInteger" use="required"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="force-ratio" minOccurs="0">
								<xs:complexType>
									<xs:attribute name="feedback-time" type="T_Time" use="optional"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="decisional-model" type="xs:string" use="required"/>
						<xs:attribute name="id" type="xs:nonNegativeInteger" use="required"/>
						<xs:attribute name="type" type="xs:string" use="required"/>
						<xs:attribute name="name" type="xs:string" use="required"/>
						<xs:attribute name="can-fly" type="xs:boolean" use="optional"/>
						<xs:attribute name="is-autonomous" type="xs:boolean" use="optional"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== dns-gh/oodevs/data/tests/test_data_unicode/physical base without unicode/Units.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<units model-version="4.8.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schemas/5.2.0/physical/Units.xsd">
  <unit decisional-model="Test model unicode  даторíйлє" id="1" name="Test pion unicode 沙发／沙發" type="Pion LOG TC2">
    <nature atlas-nature="PC" level="none" nature-app6="emergency/firefighter"/>
    <equipments>
      <equipment count="1" crew="2" type="Test equipment unicode المكتبة"/>
    </equipments>
    <sensors-range range="0"/>
    <equipments-range range="0"/>
    <crew-ranks>
      <crew-rank count="1" type="Officier"/>
      <crew-rank count="1" type="SousOfficier"/>
    </crew-ranks>
    <logistics>
      <category name="mine">
        <resource capacity="1" logistic-threshold="0" name="Test mine unicode 共通語" normalized-consumption="0"/>
      </category>
    </logistics>
    <stocks>
      <stock logistic-supply-class="Test log cat unicode 共通語" threshold="10"/>
    </stocks>
    <postures>
      <posture name="PosteReflexe" setup-time="0s" tear-down-time="0s"/>
      <posture name="Poste" setup-time="0s" tear-down-time="0s"/>
      <posture name="PosteAmenage" setup-time="0s" tear-down-time="0s"/>
      <posture name="PostePrepareGenie" setup-time="0s" tear-down-time="0s"/>
    </postures>
    <nbc decontamination-delay="1s" suit="level2"/>
    <distance-before-points>
      <distance-before-point type="urban area" value="100"/>
    </distance-before-points>
    <efficiencies combat="50" combat-support="50" counter-mobility-support="50" engineering-support="50" mobility-support="50" protection-support="50" recon="50" urban-area="50"/>
    <crossing-height height="0m"/>
  </unit>
</units>
