=== dns-gh/oodevs/data/app-data/resources/schemas/4.3.3/exercise/profiles.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" version="4.8.3">
	<xs:include schemaLocation="common.xsd"/>
	<xs:simpleType name="roleType">
		<xs:annotation>
			<xs:documentation xml:lang="en">Defines roles used together with profile.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="supervisor"/>
			<xs:enumeration value="anibas"/>
			<xs:enumeration value="eniex"/>
			<xs:enumeration value="direx"/>
			<xs:enumeration value="environment"/>
			<xs:enumeration value="analysis"/>
			<xs:enumeration value="service-gestim"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="profiles">
		<xs:annotation>
			<xs:documentation xml:lang="en">Root element, defines a list of profiles.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="profile" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="model-version" type="T_Version"/>
		</xs:complexType>
		<!-- Constraints -->
		<xs:unique name="profileNameUnicity">
			<xs:annotation>
				<xs:documentation xml:lang="en">Checks unicity of profile names.</xs:documentation>
				<xs:documentation xml:lang="fr">Vérifie l'unicité des noms de profile.</xs:documentation>
			</xs:annotation>
			<xs:selector xpath=".//profile"/>
			<xs:field xpath="@name"/>
		</xs:unique>
	</xs:element>
	<xs:complexType name="T_EntityAccessRight">
		<xs:annotation>
			<xs:documentation xml:lang="en">Defines access for an entity.</xs:documentation>
		</xs:annotation>
		<xs:attribute name="id" type="xs:nonNegativeInteger" use="required">
			<xs:annotation>
				<xs:documentation xml:lang="en">Defines the identifier of the entity for which to define access rights.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="T_AccessRights">
		<xs:annotation>
			<xs:documentation xml:lang="en">Defines a list of access rights to exercise units.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="side" type="T_EntityAccessRight" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation xml:lang="en">Defines access rights for a side.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="formation" type="T_EntityAccessRight" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation xml:lang="en">Defines access for a formation.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="automat" type="T_EntityAccessRight" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation xml:lang="en">Defines access for an automat</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="crowd" type="T_EntityAccessRight" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation xml:lang="en">Defines access for a crowd</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="population" type="T_EntityAccessRight" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation xml:lang="en">Defines access rights for a population.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="profile">
		<xs:annotation>
			<xs:documentation xml:lang="en">Defines profile information and access rights.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="rights">
					<xs:annotation>
						<xs:documentation xml:lang="en">Defines access rights over exercise units for profile.</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="readonly" type="T_AccessRights">
								<xs:annotation>
									<xs:documentation xml:lang="en">Defines read only access to exercise units (user can see but not control units).</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="readwrite" type="T_AccessRights">
								<xs:annotation>
									<xs:documentation xml:lang="en">Defines read write access to exercise units (user can control units).</xs:documentation>
								</xs:annotation>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required">
				<xs:annotation>
					<xs:documentation xml:lang="en">Defines the name of the profile, used to log in. Must be unique.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="password" type="xs:string" use="required">
				<xs:annotation>
					<xs:documentation xml:lang="en">Defines the password to be used to log in using this profile.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="supervision" type="xs:boolean" use="required">
				<xs:annotation>
					<xs:documentation xml:lang="en">Grants access to supervision operations for this profile.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="role" type="roleType" use="optional">
				<xs:annotation>
					<xs:documentation xml:lang="en">Specifies role for this profile.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== dns-gh/oodevs/data/exercises/tests/ValidationTests aux tomates/profiles.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<profiles model-version="4.8.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schemas/4.3.3/exercise/profiles.xsd">
  <profile name="Preparator" password="" supervision="true">
    <rights>
      <readonly/>
      <readwrite>
        <side id="3"/>
        <side id="1"/>
      </readwrite>
    </rights>
  </profile>
  <profile name="Automate RENS RADINT Renseigner Sur" password="" supervision="true">
    <rights>
      <readonly/>
      <readwrite>
        <side id="3"/>
        <side id="1"/>
      </readwrite>
    </rights>
  </profile>
  <profile name="Automate RENS ROEM Elge Appuyer" password="" supervision="true">
    <rights>
      <readonly/>
      <readwrite>
        <side id="3"/>
        <side id="1"/>
      </readwrite>
    </rights>
  </profile>
  <profile name="Automate RENS ROEM Brovab Appuyer" password="" supervision="true">
    <rights>
      <readonly/>
      <readwrite>
        <side id="3"/>
        <side id="1"/>
      </readwrite>
    </rights>
  </profile>
  <profile name="Automate RENS ROEM Renseigner Sur" password="" supervision="true">
    <rights>
      <readonly/>
      <readwrite>
        <side id="3"/>
        <side id="1"/>
      </readwrite>
    </rights>
  </profile>
  <profile name="Automate RENS ROHUM Renseigner Sur" password="" supervision="true">
    <rights>
      <readonly/>
      <readwrite>
        <side id="3"/>
        <side id="1"/>
      </readwrite>
    </rights>
  </profile>
  <profile name="Automate RENS ROHUM SExfiltrer" password="" supervision="true">
    <rights>
      <readonly/>
      <readwrite>
        <side id="3"/>
        <side id="1"/>
      </readwrite>
    </rights>
  </profile>
  <profile name="Automate RENS ROIM CL289 Renseigner Sur" password="" supervision="true">
    <rights>
      <readonly/>
      <readwrite>
        <side id="3"/>
        <side id="1"/>
      </readwrite>
    </rights>
  </profile>
  <profile name="Automate RENS ROIM SDTI Renseigner Sur" password="" supervision="true">
    <rights>
      <readonly/>
      <readwrite>
        <side id="3"/>
        <side id="1"/>
      </readwrite>
    </rights>
  </profile>
  <profile name="Automate TRANS Commander" password="" supervision="true">
    <rights>
      <readonly/>
      <readwrite>
        <side id="3"/>
        <side id="1"/>
      </readwrite>
    </rights>
  </profile>
  <profile name="Automate GEN Degager Obstacles Dans Zone" password="" supervision="true">
    <rights>
      <readonly/>
      <readwrite>
        <side id="3"/>
        <side id="1"/>
      </readwrite>
    </rights>
  </profile>
  <profile name="Automate GEN Faire Franchir" password="" supervision="true">
    <rights>
      <readonly/>
      <readwrite>
        <side id="3"/>
        <side id="1"/>
      </readwrite>
    </rights>
  </profile>
  <profile name="Automate GEN Franchir De Vive Force" password="" supervision="true">
    <rights>
      <readonly/>
      <readwrite>
        <side id="3"/>
        <side id="1"/>
      </readwrite>
    </rights>
  </profile>
  <profile name="Automate GEN Ouvrir Itineraires" password="" supervision="true">
    <rights>
      <readonly/>
      <readwrite>
        <side id="3"/>
        <side id="1"/>
      </readwrite>
    </rights>
  </profile>
  <profile name="Automate GEN Realiser Travaux" password="" supervision="true">
    <rights>
      <readonly/>
      <readwrite>
        <side id="3"/>
        <side id="1"/>
      </readwrite>
    </rights>
  </profile>
  <profile name="Automate GEN Reconnaitre Zone" password="" supervision="true">
    <rights>
      <readonly/>
      <readwrite>
        <side id="3"/>
        <side id="1"/>
      </readwrite>
    </rights>
  </profile>
  <profile name="Automate GEN Retablir Itineraires" password="" supervision="true">
    <rights>
      <readonly/>
      <readwrite>
        <side id="3"/>
        <side id="1"/>
      </readwrite>
    </rights>
  </profile>
  <profile name="Automate GEN Se Deployer" password="" supervision="true">
    <rights>
      <readonly/>
      <readwrite>
        <side id="3"/>
        <side id="1"/>
      </readwrite>
    </rights>
  </profile>
  <profile name="Automate NBC Armer Un Site De Decontamination" password="" supervision="true">
    <rights>
      <readonly/>
      <readwrite>
        <side id="3"/>
        <side id="1"/>
      </readwrite>
    </rights>
  </profile>
  <profile name="Automate NBC Decontaminer Une Zone" password="" supervision="true">
    <rights>
      <readonly/>
      <readwrite>
        <side id="3"/>
        <side id="1"/>
      </readwrite>
    </rights>
  </profile>
  <profile name="Automate NBC Reconnaitre Un Axe" password="" supervision="true">
    <rights>
      <readonly/>
      <readwrite>
        <side id="3"/>
        <side id="1"/>
      </readwrite>
    </rights>
  </profile>
  <profile name="Automate NBC Reconnaitre Une Zone" password="" supervision="true">
    <rights>
      <readonly/>
      <readwrite>
        <side id="3"/>
        <side id="1"/>
      </readwrite>
    </rights>
  </profile>
  <profile name="Automate ASA Defendre Itineraire" password="" supervision="true">
    <rights>
      <readonly/>
      <readwrite>
        <side id="3"/>
        <side id="1"/>
      </readwrite>
    </rights>
  </profile>
  <profile name="Automate ASA ROLAND-CAROL Defendre Site" password="" supervision="true">
    <rights>
      <readonly/>
      <readwrite>
        <side id="3"/>
        <side id="1"/>
      </readwrite>
    </rights>
  </profile>
  <profile name="Automate ASA ROLAND-CAROL Defendre Zone" password="" supervision="true">
    <rights>
      <readonly/>
      <readwrite>
        <side id="3"/>
        <side id="1"/>
      </readwrite>
    </rights>
  </profile>
  <profile name="Automate ASA ROLAND-CAROL Surveiller" password="" supervision="true">
    <rights>
      <readonly/>
      <readwrite>
        <side id="3"/>
        <side id="1"/>
      </readwrite>
    </rights>
  </profile>
  <profile name="Automate ASA HAWK Defendre Site" password="" supervision="true">
    <rights>
      <readonly/>
      <readwrite>
        <side id="3"/>
        <side id="1"/>
      </readwrite>
    </rights>
  </profile>
  <profile name="Automate ASA HAWK Defendre Zone" password="" supervision="true">
    <rights>
      <readonly/>
      <readwrite>
        <side id="3"/>
        <side id="1"/>
      </readwrite>
    </rights>
  </profile>
  <profile name="Automate ASA HAWK Surveiller" password="" supervision="true">
    <rights>
      <readonly/>
      <readwrite>
        <side id="3"/>
        <side id="1"/>
      </readwrite>
    </rights>
  </profile>
  <profile name="Automate ASA MISTRAL Defendre Site" password="" supervision="true">
    <rights>
      <readonly/>
      <readwrite>
        <side id="3"/>
        <side id="1"/>
      </readwrite>
    </rights>
  </profile>
  <profile name="Automate ASA MISTRAL Defendre Zone" password="" supervision="true">
    <rights>
      <readonly/>
      <readwrite>
        <side id="3"/>
        <side id="1"/>
      </readwrite>
    </rights>
  </profile>
  <profile name="Automate ASA MISTRAL Surveiller" password="" supervision="true">
    <rights>
      <readonly/>
      <readwrite>
        <side id="3"/>
        <side id="1"/>
      </readwrite>
    </rights>
  </profile>
  <profile name="Automate ASS Acquerir Objectifs" password="" supervision="true">
    <rights>
      <readonly/>
      <readwrite>
        <side id="3"/>
        <side id="1"/>
      </readwrite>
    </rights>
  </profile>
  <profile name="Automate ASS Reconnaitre Zones Deploiement" password="" supervision="true">
    <rights>
      <readonly/>
      <readwrite>
        <side id="3"/>
        <side id="1"/>
      </readwrite>
    </rights>
  </profile>
  <profile name="Automate ASS Se Deployer" password="" supervision="true">
    <rights>
      <readonly/>
      <readwrite>
        <side id="3"/>
        <side id="1"/>
      </readwrite>
    </rights>
  </profile>
  <profile name="Automate ABC Appuyer" password="" supervision="true">
    <rights>
      <readonly/>
      <readwrite>
        <side id="3"/>
        <side id="1"/>
      </readwrite>
    </rights>
  </profile>
  <profile name="Automate ABC Appuyer sur position" password="" supervision="true">
    <rights>
      <readonly/>
      <readwrite>
        <side id="3"/>
        <side id="1"/>
      </readwrite>
    </rights>
  </profile>
  <profile name="Automate ABC Armer Point De Controle" password="" supervision="true">
    <rights>
      <readonly/>
      <readwrite>
        <side id="3"/>
        <side id="1"/>
      </readwrite>
    </rights>
  </profile>
  <profile name="Automate ABC Attaquer" password="" supervision="true">
    <rights>
      <readonly/>
      <readwrite>
        <side id="3"/>
        <side id="1"/>
      </readwrite>
    </rights>
  </profile>
  <profile name="Automate ABC Contre Attaquer" password="" supervision="true">
    <rights>
      <readonly/>
      <readwrite>
        <side id="3"/>
        <side id="1"/>
      </readwrite>
    </rights>
  </profile>
  <profile name="Automate ABC Controler" password="" supervision="true">
    <rights>
      <readonly/>
      <readwrite>
        <side id="3"/>
        <side id="1"/>
      </readwrite>
    </rights>
  </profile>
  <profile name="Automate ABC Couvrir" password="" supervision="true">
    <rights>
      <readonly/>
      <readwrite>
        <side id="3"/>
        <side id="1"/>
      </readwrite>
    </rights>
  </profile>
  <profile name="Automate ABC Donner Coup Arret" password="" supervision="true">
    <rights>
      <readonly/>
      <readwrite>
        <side id="3"/>
        <side id="1"/>
      </readwrite>
    </rights>
  </profile>
  <profile name="Automate ABC Eclairer" password="" supervision="true">
    <rights>
      <readonly/>
      <readwrite>
        <side id="3"/>
        <side id="1"/>
      </readwrite>
